import { NextRequest, NextResponse } from "next/server";
import { callAI } from "@/lib/ai";
import { z } from "zod";

const SeedRequestSchema = z.object({
  concept: z.string(),
  difficulty: z.enum(["beginner", "intermediate", "advanced"]),
});

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { concept, difficulty } = SeedRequestSchema.parse(body);

    const systemPrompt = `You are a coding educator. Generate a single, self-contained JavaScript/TypeScript function that is PEDAGOGICALLY DESIGNED to expose the full complexity of [${concept}] at [${difficulty}] level. 
The function must: have at least one non-obvious edge case, use real-world naming (not foo/bar), be 15-40 lines, include NO inline comments (the student must figure it out). 
Return only the raw function code, nothing else.`;

    const rawResponse = await callAI({
      task: "lineExplanation", // Using a quality-oriented model as per PRD for complex generation
      messages: [{ role: "system", content: systemPrompt }],
      temperature: 0.7,
      maxTokens: 2000,
    });

    // Strip markdown if AI wraps it
    let code = rawResponse.trim();
    if (code.startsWith("```")) {
      const lines = code.split("\n");
      code = lines.slice(1, -1).join("\n").trim();
    }

    // Validation: must be non-empty string, must contain 'function' or '=>'
    if (!code || (!code.includes("function") && !code.includes("=>"))) {
      throw new Error("Invalid code generated by AI");
    }

    return NextResponse.json({ code });
  } catch (error) {
    console.error("Seed generation error:", error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Failed to generate seed project" },
      { status: 500 }
    );
  }
}
